language: csharp
solution: unity.sln
git:
  submodules: false
notifications:
  email: false
env:
  matrix:
    - MONO_VERSION="3.5.0"
before_install:
    - "npm install unity-solution-2 -g"
    - "unitysolution ./SDM-Intersection-Simulator Standalone" #due to nuget restore
    #- mozroots --import --sync
    #- mv -f src/.nuget/NuGet.mono.targets src/.nuget/NuGet.targets
script:
    - "xbuild /p:Configuration=Debug unity.sln"
    #- mono ../lib/xunit/xunit.console.clr4.x86.exe ./Tests/bin/Debug/CI.Demo.Tests.dll
branches:
    only:
        - master
        - dev
